---
- name: forward-proxy
  hosts: localhost
  become: true
  tasks:
    - name: install httpd
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Enable httpd
      ansible.builtin.service:
        name: httpd
        enabled: yes

    - name: Configure forward-proxy
      ansible.builtin.copy:
        src: files/proxy.conf
        dst: /etc/httpd/conf.d/proxy.conf

    - name: restart httpd
      ansible.builtin.service:
        name: httpd
        state: restarted