---
- name: Update DNS record via REST API
  hosts: localhost
  gather_facts: no
  vars:
    domain: "aappll"
    api_token: "QG4TQhHWqf_H8RA"
  roles:
    - get_public_ip

  tasks:
    - name: Update DNS record via REST API
      uri:
        url: "https://f5.si/update.php?domain={{ domain }}&password={{ api_token }}&ip={{ ip_address }}"
        method: GET
        return_content: yes
      register: dns_update_response

    - name: Show API Response
      debug:
        var: dns_update_response.content
