---
- name: Retrieve public IP of AWS EC2 instance #
  hosts: all
  gather_facts: no
  tasks:
    - name: Get IP address in EC2
      amazon.aws.ec2_instance_info:
      register: ec2_instance_info

    - name: Show IP address
      ansible.builtin.debug:
        msg: ec2_instance_info