---
- name: Retrieve EC2 information
  hosts: all
  gather_facts: no
  tasks:
   - name: Gather information about all instances
     amazon.aws.ec2_instance_info:
     register: ec2_info

   - name: Show ec2 information
     ansible.builtin.debug:
       var: ec2_info