---
- name: Retrieve EC2 information
  hosts: all
  gather_facts: no
  tasks:
   - name: Gather information about all instances
     register: ec2_info
     amazon.aws.ec2_instance_info:


   - name: Show ece information
     ansible.builtin.debug:
     msg: ec2_info