---
- name: Get public IP using AWS metadata service
  uri:
    url: "http://169.254.169.254/latest/meta-data/public-ipv4"
    method: GET
    return_content: yes
  register: public_ip_response

- name: Set public IP as fact
  set_fact:
    public_ip: "{{ public_ip_response.content }}"
